### ISSUE TITLE
Allow inject service in constructor from Nette DI

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#10]
Constructor in `BaseEndpoint` is final, but why?
I want to use most readable and clear feature and it is constructor DI injection.
Is possible to allow constructor injection in custom endpoints?

cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole I think it can be solved like it: https://github.com/baraja-core/structured-api/commit/20b256cdaac5ff7da6696cd62068cd7ed747dca8

This commit remove required constructor, but contain back support for `@inject` annotation.

What do you think about?

Thanks.

**Comment by sitole** [comment]
Nice.

But i´am confused with method `injectContainer`. Why we need container in endpoint class?
Its messy and anti-pattern to let controller hold DI container. Controller requires only some dependencies in inject properties or constructor injection.

DI container property is magical for example in tests.

cc @janbarasek

**Comment by sitole** [comment]
We can inject properties from outside (as default DI handler).

**Comment by janbarasek** [comment]
@Sitole I don't think it's possible to implement full support for your proposal at this time.

Injectable dependecies is operated externally now: https://github.com/baraja-core/structured-api/commit/94ef68b1c9df0aed244939c37391ac989268a4db

But Container property should be keep for back support: https://github.com/baraja-core/structured-api/blob/master/src/Endpoint/BaseEndpoint.php#L29

Can I close issue?

**Comment by sitole** [comment]
Super. Yes you can.

**Comment by janbarasek** [comment]
Thanks!
