### ISSUE TITLE
Implement custom HTTP response codes

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#11]
For error response i want to return custom error code (400 by default).
It brings simplicity with front-end development and global error tracking.

cc @janbarasek

**Comment by janbarasek** [comment]
I think HTTP code can be rewrited from key `code` by application response:

https://github.com/baraja-core/structured-api/blob/628f7de432f081b1b6d2980b11f0d62ecfd4f813/src/Endpoint/BaseEndpoint.php#L119

Or interface `Endpoint` (https://github.com/baraja-core/structured-api/blob/master/src/Endpoint/Endpoint.php) should implement new method `setHttpCode()`.

What do you think about?

**Comment by janbarasek** [comment]
@Sitole I implement it by this commit: https://github.com/baraja-core/structured-api/commit/7de2602221241b7987bee9a44ba05bbf9aeef36f

What do you think about?

cc @HamAndRock
