### ISSUE TITLE
Put method alias

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#3]
Create alias for HTTP Put method. This method is traditionally used as method for data update operation and method named `putArticle()` is little bit confused. New behavior should accept `updateArticle()` method.

The put method should be acceptable for backward support.
cc @janbarasek

**Comment by sitole** [comment]
Maybe we should support `get` alias for `action`.
@janbarasek

**Comment by janbarasek** [comment]
@Sitole Added native support, thanks.

Commit: https://github.com/baraja-core/structured-api/commit/d6c1afcf70cb91adede3bde5fc5e31a3eb76c768

By the way I think alias `get` should be unsupported, because prefix `get` can means `getter` and it can make misunderstand.

Thanks.
