### ISSUE TITLE
Add support for boolean parameters in GET

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#4]
Add native support for boolean parameters. Support `1/0` and `true/false` as boolean.

`/api/v1/articles/?onlyVisible=false` handled by `actionDefault(bool $onlyVisible)`
parameters `$onlyVisible` is true (string converted to bool) but should be false.

cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole Implemented, thanks.

Source: https://github.com/baraja-core/structured-api/commit/97d3d86746d93f7939f3ae7cc65fae2f32548e0d
