### ISSUE TITLE
Add support for request body object

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#5]
In many cases, we need data type verification, but at this time you have to use a simple array to check each index yourself. This is stressful and adds extra junk code to the application, which is duplicated in several places.

Many frameworks implement a method of converting JSON bodies into a simple DTO object, which, in addition to PHP 7.4, can contain data types directly in class attributes, so there is no need to create complex getters and setters that are easy to understand and it is Boilerplate code.

Example use:
```php
// simple DTO object
class ArticleRequestBody {
	public string $name;
	public DateTimeImmutable $created;
	public bool $public = true;
	public string ?$description = null;
}

// Endpoint handler
public function postDefault(ArticleRequestBody $requestBody): void
{
	// Magic here
	var_dump($requestBody->name);
}
```

Extra verification as the length of the name is checked in the entity or endpoint.
cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole I implemented native support with parsing property annotations, constructor inspection, and circular dependency checker.

Source: https://github.com/baraja-core/service-method-invoker/commit/1ed71533ace91bd05160b9a7b33cbd5a8ba3045a

Thanks.
