### ISSUE TITLE
Separate EntityManager

### ISSUE THREAD

**Issue by sitole** [baraja-core/structured-api#7]
EntityManager is only an optional dependency and should not be in the API core.
Yes Doctrine is used very often, but not always, and its shadow dependence.

cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole I think in case of `EntityManager` does not exist, method can throw `\RuntimeException` like this:

![Snímek obrazovky 2020-03-23 v 17 50 50](https://user-images.githubusercontent.com/4738758/77341326-d6546600-6d2e-11ea-86c6-ebc33b71bd5b.png)

Thanks.

**Comment by sitole** [comment]
This is a compromise. But I still think it's not good to use some magic addiction. This lib handles API requests and is not an abbreviation for the database layer.

**Comment by sitole** [comment]
> This is a compromise. But I still think it's not good to use some magic addiction. This lib handles API requests and is not an abbreviation for the database layer.

PHPStan is very strict (i mean it´s right) with dependencies in code. `class_exists(EntityManager::class)` throws error, because its shadow dependence.

**Comment by janbarasek** [comment]
@Sitole Ok, thanks. In your PR it was removed and I think we can do it.
